services:
  backend:
    container_name: backend
    image: 850995544968.dkr.ecr.eu-north-1.amazonaws.com/webapp:backend-prod-latest
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_PORT_SSL=${FRONTEND_PORT_SSL}
      - PORT=${BACKEND_PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB_NAME}
      - AI_KEY=${AI_KEY}
      - ENV=production
    restart: always
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    container_name: frontend
    image: 850995544968.dkr.ecr.eu-north-1.amazonaws.com/webapp:frontend-prod-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./ssl/:/etc/ssl/
      - ./frontend/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:17.0
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - pgdataprod:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdataprod:
