services:
  backend:
    container_name: backend
    image: 850995544968.dkr.ecr.eu-north-1.amazonaws.com/webapp:backend-latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB_NAME}
      - AI_KEY=${AI_KEY}
      - ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    container_name: frontend
    image: 850995544968.dkr.ecr.eu-north-1.amazonaws.com/webapp:frontend-latest
    ports:
      - "${FRONTEND_PORT_DEV}:${FRONTEND_PORT_DEV}"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: 850995544968.dkr.ecr.eu-north-1.amazonaws.com/webapp:postgres
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
