services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_PORT_SSL=${FRONTEND_PORT_SSL}
      - PORT=${BACKEND_PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB_NAME}
      - AI_KEY=${AI_KEY}
      - ENV=production
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_SSL}:443"
    volumes:
      - ./etc/letsencrypt/live/tuukkasalonen.fi:/etc/cert/
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:17.0
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata: