# Use the official NGINX image from the Docker Hub
FROM nginx:1.27

# Copy custom NGINX configuration file and entrypoint script
COPY ./nginx.conf.template /etc/nginx/nginx.conf.template
COPY ./entrypoint.sh /entrypoint.sh

# Make entrypoint script executable
RUN chmod +x /entrypoint.sh

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext-base

# Use the entrypoint script to substitute variables and start NGINX
ENTRYPOINT ["/entrypoint.sh"]